name:
    css: '#productTitle'
    type: Text


Description:
    css: '#productDescription'
    type: Text

Details:
    css: '#feature-bullets'
    type: Text
    

Descriptif technique:
    css: '.col1 tr'
    multiple: true
    type: Text
    children:
        info:
            css: '.label'
            type: Text
        value:
            css: '.value'
            type: Text

