
    
freq_bought:
    css: '#sims-fbt-form .a-size-base.a-link-normal'
    type: Text

freq_bought_link:
    css: '#sims-fbt-form .a-size-base.a-link-normal'
    type: Link

link_to_all_reviews:
    css: 'div.card-padding a.a-link-emphasis'
    type: Link